/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package formaKupac;

import domain.Kupac;
import domain.Mesto;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import kontoler.KlijentKontroler;

/**
 *
 * @author jovan
 */
  

    public class DetaljiKupca extends javax.swing.JDialog {

        Kupac kupac;

        /**
         * Creates new form DetaljiKupca
         */
        public DetaljiKupca(JDialog parent, boolean modal, Kupac k) {
            super(parent, modal);
            initComponents();
            setLocationRelativeTo(null);
            setTitle("Detalji kupca");
            kupac = k;
            txtIme1.setText(kupac.getIme());
            txtPrezime1.setText(kupac.getPrezime());
            txtEmail1.setText(kupac.getEmail());
            txtTelefon1.setText(kupac.getTelefon());
            popuniMesta();
            cmbMesto1.getModel().setSelectedItem(kupac.getMesto());
            txtIme1.setEditable(false);
            txtPrezime1.setEditable(false);
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        cmbMesto = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIme1 = new javax.swing.JTextField();
        txtPrezime1 = new javax.swing.JTextField();
        txtEmail1 = new javax.swing.JTextField();
        txtTelefon1 = new javax.swing.JTextField();
        cmbMesto1 = new javax.swing.JComboBox();
        btnZatvori = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();

        cmbMesto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ime:");

        jLabel2.setText("Prezime:");

        jLabel3.setText("Email:");

        jLabel4.setText("Telefon:");

        jLabel5.setText("Mesto:");

        cmbMesto1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnZatvori.setText("Zatvori");
        btnZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZatvoriActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obriši kupca");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni kupca");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIme1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrezime1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefon1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMesto1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnZatvori)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisi)
                        .addGap(29, 29, 29)
                        .addComponent(btnIzmeni)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrezime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTelefon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbMesto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisi)
                    .addComponent(btnIzmeni)
                    .addComponent(btnZatvori))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZatvoriActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnZatvoriActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int result = JOptionPane.showConfirmDialog(
                this,
                "Da li ste sigurni da želite da obrišete ovog kupca?",
                "Potvrda",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.NO_OPTION) {
            return;
        }
        if (result == JOptionPane.YES_OPTION) {
            try {

                KlijentKontroler.getInstance().obrisiKupac(kupac);

                PretragaKupca pk = (PretragaKupca) getParent();
                pk.refresujTabelu();
                JOptionPane.showMessageDialog(
                        this,
                        "Kupac je uspešno obrisan.",
                        "Uspešno",
                        JOptionPane.INFORMATION_MESSAGE
                );
                this.dispose();
            } catch (Exception ex) {
                if (ex.getMessage().contains("foreign key")) {
                    JOptionPane.showMessageDialog(
                            this,
                            "Kupac ne može biti obrisan jer postoje računi povezani sa ovim kupcem.",
                            "Brisanje nije moguće",
                            JOptionPane.WARNING_MESSAGE
                    );
                } else {
                    JOptionPane.showMessageDialog(
                            this,
                            ex.getMessage(),
                            "Greška",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }
        }
    
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        try {
            if (txtIme1.getText().isEmpty() || txtPrezime1.getText().isEmpty()
                    || txtEmail1.getText().isEmpty()
                    || txtTelefon1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "Popunite sva obavezna polja.",
                        "Upozorenje",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }
            if (!txtEmail1.getText().trim().contains("@")) {

                JOptionPane.showMessageDialog(
                        this,
                        "Unesite ispravnu e-mail adresu.",
                        "Upozorenje",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
            }
            if (!txtTelefon1.getText().trim().matches("\\d+")) {

                JOptionPane.showMessageDialog(
                        this,
                        "Telefon može sadržati samo cifre.",
                        "Upozorenje",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
            }
            String email = txtEmail1.getText().trim();
            String telefon = txtTelefon1.getText().trim();
            Mesto mesto = (Mesto) cmbMesto1.getSelectedItem();

            kupac.setEmail(email);
            kupac.setTelefon(telefon);
            kupac.setMesto(mesto);

            KlijentKontroler.getInstance().promeniKupac(kupac);
            PretragaKupca pk = (PretragaKupca) getParent();
            pk.refresujTabelu();
            JOptionPane.showMessageDialog(
                    this,
                    "Podaci o kupcu su uspešno izmenjeni.",
                    "Uspešno",
                    JOptionPane.INFORMATION_MESSAGE
            );
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();

            JOptionPane.showMessageDialog(
                    this,
                    "Podatke o kupcu nije moguće izmeniti.",
                    "Greška",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnZatvori;
    private javax.swing.JComboBox cmbMesto;
    private javax.swing.JComboBox cmbMesto1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtIme1;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtPrezime1;
    private javax.swing.JTextField txtTelefon;
    private javax.swing.JTextField txtTelefon1;
    // End of variables declaration//GEN-END:variables

    private void popuniMesta() {
        try {
            ArrayList<Mesto> mesta = KlijentKontroler.getInstance().vratiSvaMesta();

            cmbMesto1.removeAllItems();

            for (Mesto mesto : mesta) {
                cmbMesto1.addItem(mesto);
            }

        } catch (Exception ex) {
            Logger.getLogger(NoviKupac.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
