/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domain.Knjiga;
import domain.Kupac;
import domain.Prodavac;
import domain.Racun;
import domain.StavkaRacuna;
import formaKnjiga.NovaKnjiga;
import formaKnjiga.PretragaKnjiga;
import formaKupac.NoviKupac;
import formaKupac.PretragaKupca;
import formaRacun.PretragaRacun;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontoler.KlijentKontroler;
import modeli.ModelTabeleStavkaRacuna;
import sesija.Sesija;
import java.awt.Color;
import javax.swing.JTextField;
import util.PlaceholderUtil;

/**
 *
 * @author jovan
 */
public class KlijentskaForma extends javax.swing.JFrame {

    Prodavac ulogovani;
    private double ukupanIznos;
    private ArrayList<Kupac> sviKupci;
    private ArrayList<Knjiga> sveKnjige;

    /**
     * Creates new form KlijenstkaForma
     */
    public KlijentskaForma() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Knjižara - Novi račun");
        this.ulogovani = Sesija.getInstance().getUlogovani();
        lblUlogovani.setText(ulogovani.toString());
        popuniKupce();
        popuniKnjige();
        PlaceholderUtil.postaviPlaceholder(txtPretragaKupca, "Unesite ime ili prezime...");
        PlaceholderUtil.postaviPlaceholder(txtPretragaKnjige, "Unesite naziv ili autora...");
        txtCena.setEditable(false);
        txtUkupanIznos.setEditable(false);
        tblStavkeRacuna.setModel(new ModelTabeleStavkaRacuna());
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        txtDatum.setText(sdf.format(new Date()));
        btnDodajStavku.setToolTipText("Dodaje novu stavku računa");
        btnSAcuvaj.setToolTipText("Čuva novi račun");
        btnOdjava.setToolTipText("Odjava iz sistema");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        lblUlogovani = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        cmbKupac = new javax.swing.JComboBox();
        txtUkupanIznos = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbKnjiga = new javax.swing.JComboBox();
        txtKolicina = new javax.swing.JTextField();
        txtCena = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavkeRacuna = new javax.swing.JTable();
        btnDodajStavku = new javax.swing.JButton();
        btnObrisiStavku = new javax.swing.JButton();
        txtPretragaKnjige = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnSAcuvaj = new javax.swing.JButton();
        txtPretragaKupca = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnOdjava = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miNoviKupac = new javax.swing.JMenuItem();
        miPretragaKupca = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        miNovaKnjiga = new javax.swing.JMenuItem();
        miPretraziKnjigu = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Vino:");

        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Kolicina:");

        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("Cena:");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("File");
        jMenuBar5.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar5.add(jMenu10);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblUlogovani.setForeground(new java.awt.Color(51, 0, 51));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Račun"));

        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Kupac:");

        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Datum izdavanja:");

        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Ukupan iznos:");

        cmbKupac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbKupac.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbKupacItemStateChanged(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavke računa"));

        jLabel7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel7.setText("Knjiga");

        jLabel8.setForeground(new java.awt.Color(51, 102, 255));
        jLabel8.setText("Količina:");

        jLabel9.setForeground(new java.awt.Color(51, 102, 255));
        jLabel9.setText("Cena:");

        cmbKnjiga.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbKnjiga.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbKnjigaItemStateChanged(evt);
            }
        });

        txtKolicina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKolicinaKeyReleased(evt);
            }
        });

        tblStavkeRacuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavkeRacuna);

        btnDodajStavku.setBackground(new java.awt.Color(204, 204, 204));
        btnDodajStavku.setText("Dodaj stavku računa");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnObrisiStavku.setBackground(new java.awt.Color(204, 204, 204));
        btnObrisiStavku.setText("Obriši stavku računa");
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuActionPerformed(evt);
            }
        });

        txtPretragaKnjige.setBackground(new java.awt.Color(245, 245, 245));
        txtPretragaKnjige.setToolTipText("Pretraži knjigu");
        txtPretragaKnjige.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaKnjigeKeyReleased(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(0, 51, 255));
        jLabel14.setText("Pretraga knjige:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnDodajStavku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnObrisiStavku)
                .addGap(129, 129, 129))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(27, 27, 27)
                        .addComponent(cmbKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKolicina)
                            .addComponent(txtCena))))
                .addGap(18, 18, 18)
                .addComponent(txtPretragaKnjige)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(69, 69, 69))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPretragaKnjige, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObrisiStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        btnSAcuvaj.setBackground(new java.awt.Color(204, 204, 204));
        btnSAcuvaj.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSAcuvaj.setText("SAČUVAJ RAČUN");
        btnSAcuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAcuvajActionPerformed(evt);
            }
        });

        txtPretragaKupca.setBackground(new java.awt.Color(245, 245, 245));
        txtPretragaKupca.setColumns(25);
        txtPretragaKupca.setToolTipText("Pretraži kupca");
        txtPretragaKupca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaKupcaKeyReleased(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(0, 51, 255));
        jLabel13.setText("Pretraga kupca:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(btnSAcuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                            .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(86, 86, 86)
                            .addComponent(cmbKupac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPretragaKupca, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(107, 107, 107))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPretragaKupca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(61, 61, 61)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSAcuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Prodavac:");

        btnOdjava.setBackground(new java.awt.Color(204, 204, 204));
        btnOdjava.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOdjava.setText("ODJAVI SE");
        btnOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjavaActionPerformed(evt);
            }
        });

        jMenu1.setBackground(new java.awt.Color(204, 0, 51));
        jMenu1.setText("Kupac");

        miNoviKupac.setText("Novi kupac");
        miNoviKupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNoviKupacActionPerformed(evt);
            }
        });
        jMenu1.add(miNoviKupac);

        miPretragaKupca.setText("Pretraga kupca");
        miPretragaKupca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaKupcaActionPerformed(evt);
            }
        });
        jMenu1.add(miPretragaKupca);

        jMenuBar1.add(jMenu1);

        jMenu6.setText("Knjiga");

        miNovaKnjiga.setText(" Nova knjiga");
        miNovaKnjiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovaKnjigaActionPerformed(evt);
            }
        });
        jMenu6.add(miNovaKnjiga);

        miPretraziKnjigu.setText("Pretraga knjige");
        miPretraziKnjigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretraziKnjiguActionPerformed(evt);
            }
        });
        jMenu6.add(miPretraziKnjigu);

        jMenuBar1.add(jMenu6);

        jMenu11.setText(" Račun");

        jMenuItem1.setText("Pretraga računa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem1);

        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(356, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUlogovani, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOdjava)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUlogovani)
                    .addComponent(jLabel10)
                    .addComponent(btnOdjava))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNoviKupacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNoviKupacActionPerformed
        new NoviKupac(this, true).setVisible(true);
    }//GEN-LAST:event_miNoviKupacActionPerformed

    private void miPretragaKupcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaKupcaActionPerformed
        new PretragaKupca(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaKupcaActionPerformed

    private void miNovaKnjigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovaKnjigaActionPerformed
        new NovaKnjiga(this, true).setVisible(true);
    }//GEN-LAST:event_miNovaKnjigaActionPerformed

    private void miPretraziKnjiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretraziKnjiguActionPerformed
        new PretragaKnjiga(this, true).setVisible(true);
    }//GEN-LAST:event_miPretraziKnjiguActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new PretragaRacun(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjavaActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da se odjavite iz sistema?",
                "Potvrda", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            try {
                KlijentKontroler.getInstance().odjava(ulogovani);
                JOptionPane.showMessageDialog(
                        this,
                        "Uspešno ste se odjavili.",
                        "Uspešno",
                        JOptionPane.INFORMATION_MESSAGE
                );
                new LoginForma().setVisible(true);
                Sesija.getInstance().setUlogovani(null);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(KlijentskaForma.class.getName()).log(Level.SEVERE, null, ex);

                JOptionPane.showMessageDialog(
                        this,
                        "Odjava nije uspela.",
                        "Greška",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btnOdjavaActionPerformed

    private void txtPretragaKupcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaKupcaKeyReleased

        String tekst = txtPretragaKupca.getText().trim();

        if (tekst.equals("Unesite ime ili prezime...")) {
            return;
        }

        tekst = tekst.toLowerCase();

        cmbKupac.removeAllItems();

        for (Kupac k : sviKupci) {

            String naziv = (k.getIme() + " " + k.getPrezime()).toLowerCase();

            if (naziv.contains(tekst)) {
                cmbKupac.addItem(k);
            }
        }

    }//GEN-LAST:event_txtPretragaKupcaKeyReleased

    private void btnSAcuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAcuvajActionPerformed
        try {
            if (txtDatum.getText().isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "Unesite datum izdavanja računa.",
                        "Upozorenje",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }
            Kupac kupac = (Kupac) cmbKupac.getSelectedItem();
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            Date datumIsporuke = sdf.parse(txtDatum.getText());
            ModelTabeleStavkaRacuna mt = (ModelTabeleStavkaRacuna) tblStavkeRacuna.getModel();

            Racun racun = new Racun(-1, datumIsporuke, ukupanIznos, kupac, ulogovani, mt.getLista());

            KlijentKontroler.getInstance().sacuvajRacun(racun);

            txtDatum.setText("");
            txtUkupanIznos.setText("");
            ukupanIznos = 0;
            mt.getLista().clear();
            mt.fireTableDataChanged();
            JOptionPane.showMessageDialog(
                    this,
                    "Račun je uspešno sačuvan.",
                    "Uspešno",
                    JOptionPane.INFORMATION_MESSAGE
            );

            txtDatum.setText(sdf.format(new Date()));
            osveziKupce(null);
            osveziKnjige(null);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Račun nije moguće sačuvati.",
                    "Greška",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnSAcuvajActionPerformed

    private void txtPretragaKnjigeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaKnjigeKeyReleased
        String tekst = txtPretragaKnjige.getText().trim();

        if (tekst.equals("Unesite naziv ili autora...")) {
            return;
        }

        tekst = tekst.toLowerCase();

        cmbKnjiga.removeAllItems();

        for (Knjiga k : sveKnjige) {

            String naziv = (k.getNaziv() + " " + k.getAutor()).toLowerCase();

            if (naziv.contains(tekst)) {
                cmbKnjiga.addItem(k);
            }
        }
    }//GEN-LAST:event_txtPretragaKnjigeKeyReleased

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed
        int row = tblStavkeRacuna.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Izaberite stavku koju želite da obrišete.",
                    "Upozorenje",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        if (row >= 0) {
            ModelTabeleStavkaRacuna mt = (ModelTabeleStavkaRacuna) tblStavkeRacuna.getModel();
            mt.obrisiStavku(row);

            ukupanIznos = mt.vratiUkupanIznos();
            txtUkupanIznos.setText(String.valueOf(ukupanIznos) + "din");
        }
    }//GEN-LAST:event_btnObrisiStavkuActionPerformed

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        if (txtKolicina.getText().isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Unesite količinu knjiga.",
                    "Upozorenje",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        Knjiga knjiga = (Knjiga) cmbKnjiga.getSelectedItem();
        int kolicina = Integer.parseInt(txtKolicina.getText());
        double cena = Double.parseDouble(txtCena.getText());

        StavkaRacuna sr = new StavkaRacuna(null, -1, kolicina, knjiga.getCena(), cena, knjiga);

        ModelTabeleStavkaRacuna mt = (ModelTabeleStavkaRacuna) tblStavkeRacuna.getModel();
        mt.dodajStavku(sr);

        ukupanIznos = mt.vratiUkupanIznos();
        txtUkupanIznos.setText(String.valueOf(ukupanIznos) + "din");
        osveziKnjige(knjiga);
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void txtKolicinaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKolicinaKeyReleased
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {

            if (txtKolicina.getText().isEmpty()) {
                return;
            }

            Knjiga knjiga = (Knjiga) cmbKnjiga.getSelectedItem();
            int kolicina = Integer.parseInt(txtKolicina.getText());

            if (kolicina == 0) {
                txtKolicina.setText("");
                txtCena.setText("");
                return;
            }

            txtCena.setText(String.valueOf(kolicina * knjiga.getCena()));

        } else {
            txtKolicina.setText("");
            txtCena.setText("");
        }
    }//GEN-LAST:event_txtKolicinaKeyReleased

    private void cmbKnjigaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbKnjigaItemStateChanged

        if (cmbKnjiga.getSelectedItem() != null) {

            if (txtKolicina.getText().isEmpty()) {
                return;
            }

            Knjiga knjiga = (Knjiga) cmbKnjiga.getSelectedItem();
            int kolicina = Integer.parseInt(txtKolicina.getText());

            if (kolicina == 0) {
                txtKolicina.setText("");
                txtCena.setText("");
                return;
            }

            txtCena.setText(String.valueOf(kolicina * knjiga.getCena()));
        }
    }//GEN-LAST:event_cmbKnjigaItemStateChanged

    private void cmbKupacItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbKupacItemStateChanged

    }//GEN-LAST:event_cmbKupacItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnOdjava;
    private javax.swing.JButton btnSAcuvaj;
    private javax.swing.JComboBox cmbKnjiga;
    private javax.swing.JComboBox cmbKupac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenuItem miNovaKnjiga;
    private javax.swing.JMenuItem miNoviKupac;
    private javax.swing.JMenuItem miPretragaKupca;
    private javax.swing.JMenuItem miPretraziKnjigu;
    private javax.swing.JTable tblStavkeRacuna;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtKolicina;
    private javax.swing.JTextField txtPretragaKnjige;
    private javax.swing.JTextField txtPretragaKupca;
    private javax.swing.JTextField txtUkupanIznos;
    // End of variables declaration//GEN-END:variables

    public void popuniKupce() {

        try {

            sviKupci = KlijentKontroler.getInstance().getAllKupac();

            cmbKupac.removeAllItems();

            for (Kupac k : sviKupci) {
                cmbKupac.addItem(k);
            }

        } catch (Exception ex) {
            Logger.getLogger(KlijentskaForma.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void popuniKnjige() {
        try {

            sveKnjige = KlijentKontroler.getInstance().getAllKnjige();

            cmbKnjiga.removeAllItems();

            for (Knjiga k : sveKnjige) {
                cmbKnjiga.addItem(k);
            }

        } catch (Exception ex) {
            Logger.getLogger(KlijentskaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void osveziKupce(Kupac selektovani) {

        cmbKupac.removeAllItems();

        for (Kupac k : sviKupci) {
            cmbKupac.addItem(k);
        }

        if (selektovani != null) {
            cmbKupac.setSelectedItem(selektovani);
        }

        txtPretragaKupca.setText("");
    }

    private void osveziKnjige(Knjiga selektovana) {

        cmbKnjiga.removeAllItems();

        for (Knjiga k : sveKnjige) {
            cmbKnjiga.addItem(k);
        }

        if (selektovana != null) {
            cmbKnjiga.setSelectedItem(selektovana);
        }

        txtPretragaKnjige.setText("");
    }
}
